### ISSUE TITLE
use Family class in the benchmark for ECX

### ISSUE THREAD

**Issue by loudoweb** [eliasku/ecx-benchmarks#2]
Why the ECX benchmark doesn't use Family class like this [System](https://github.com/eliasku/ecx/blob/master/test/ecx/EmptySystem.hx#L8) ? I saw that the Ash and Edge benchmarks use it, so it would be great to have a comparison with the family matching method.
Thanks.

**Comment by eliasku** [comment]
Hi! Cool someone looked at that, will be added 👍

**Comment by loudoweb** [comment]
Thanks. Keep up the good work.

**Comment by eliasku** [comment]
@loudoweb done

**Comment by eliasku** [comment]
@loudoweb BTW, now benchmarks are for "iterating" case: getting components and processing the data. Later I will add more benchmark methods for Composing / Matching / Removing

**Comment by eliasku** [comment]
I think I should close this issue and create new issue for "more benchmark methods for Composing / Matching / Removing"
