### ISSUE TITLE
compile benchmarks + hardware

### ISSUE THREAD

**Issue by PDeveloper** [eliasku/ecx-benchmarks#3]
I'd like to give the benchmarks a run myself locally, but to be honest, I haven't seen this kind of a project structure anywhere... (Can't find a .hxml file or similar build files for other systems)

Also, what hardware are you running the benchmarks on currently?

**Comment by eliasku** [comment]
@PDeveloper I've updated README file with more information.
https://github.com/eliasku/ecx-benchmarks/blob/master/README.md

What OS are you using? What haxe version?
Running on Windows is not available right now, but is not hard task to do. I will have free time on Saturday, so I'm going to add Windows support and will test it on VirtualBox

**Comment by PDeveloper** [comment]
Okay nice!

Yeah, Windows would be great!
(and using Haxe 3.3.0)

**Comment by eliasku** [comment]
@PDeveloper done for Windows. I think there will be some blockers on your path, but report them here.

_But anyway I should provide detailed instruction later._

**Comment by PDeveloper** [comment]
Nice!

Build works for Eskimo, but for ecx I'm getting:

```
src/ecs/benchmarks/ecx/EcxPosition1.hx:3: characters 7-27 : Type not found : ecx.storage.AutoComp
src/ecs/benchmarks/Benchmarks.hx:9: lines 9-147 : Defined in this class
src/ecs/benchmarks/ecx/EcxPosition3.hx:3: characters 7-27 : Type not found : ecx.storage.AutoComp
src/ecs/benchmarks/Benchmarks.hx:9: lines 9-147 : Defined in this class
src/ecs/benchmarks/EcsTest.hx:42: characters 15-36 : ecs.benchmarks.ecx.EcxTests does not have a constructor
src/ecs/benchmarks/EcsTest.hx:47: characters 8-18 : ecs.benchmarks.TestLibrary has no field setup
src/ecs/benchmarks/EcsTest.hx:49: characters 12-23 : ecs.benchmarks.TestLibrary has no field update
src/ecs/benchmarks/EcsTest.hx:55: characters 8-20 : ecs.benchmarks.TestLibrary has no field dispose
```

**Comment by eliasku** [comment]
@PDeveloper hi, thanks for report. It should be `import ecx.AutoComp`.
Use `develop` branch for `ecx` and `ecx-benchmarks`

**Comment by PDeveloper** [comment]
Hey!

It seems that the latest ecx-benchmarks/develop branch is trying to process the test cases in a macro? I have a `@:genericBuild` class part of the Eskimo core, which isn't available in macros.

**Comment by PDeveloper** [comment]
Nice, now it works! :+1:
